import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "@/styles/globals.css";

const barlow = Barlow({weight:"400",subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
